### ISSUE TITLE
fails to parse command args

### ISSUE THREAD

**Issue by balluh** [ndaba1/gommander#15]
Error:
```bash
 ~/development/go/owox  go run . account add                                                           ✔ 
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/ndaba1/gommander.(*Parser).getArgMatches(0xc000115bf0, {0xc00002a360, 0x3, 0xa0?}, {0xc000114d70, 0x0, 0x8?})
	/home/anon/go/pkg/mod/github.com/ndaba1/gommander@v0.1.5/parser.go:447 +0x1457
github.com/ndaba1/gommander.(*Parser).parseCmd(0xc000165bf0, {0xc000164d70?, 0x0, 0x37?})
	/home/anon/go/pkg/mod/github.com/ndaba1/gommander@v0.1.5/parser.go:381 +0xb7
github.com/ndaba1/gommander.(*Parser).parse(0xc000165bf0, {_, _, _})
	/home/anon/go/pkg/mod/github.com/ndaba1/gommander@v0.1.5/parser.go:319 +0x1d3
github.com/ndaba1/gommander.(*Command)._parse(0xc00013e2c0, {0xc00013e840?, 0xc000115e08?, 0x52e67a?})
	/home/anon/go/pkg/mod/github.com/ndaba1/gommander@v0.1.5/gommander.go:360 +0x19a
github.com/ndaba1/gommander.(*Command).Parse(...)
	/home/anon/go/pkg/mod/github.com/ndaba1/gommander@v0.1.5/gommander.go:413
main.main()
	/home/anon/development/go/owox/owox.go:66 +0x7e9
exit status 2
```
Code:
![](https://media.discordapp.net/attachments/984427800322772994/989567564193603714/unknown.png)

**Comment by ndaba1** [comment]
Thanks for opening the issue. I just patched it and released a new version. Update the package, it should work fine now.
